### ISSUE TITLE
How do I run your program?

### ISSUE THREAD

**Issue by SherHype** [Zj-BinXia/BBCU#3]
After reading your paper, I found that your work is very good, so I wanted to try running your code. But I find that the dataset always has problems when running the code, can I give you the dataset directory information or the download link of the collated dataset?

**Comment by Zj-BinXia** [comment]
Hi, thanks for your interest. You can  prepare datasets as https://github.com/XPixelGroup/BasicSR/blob/master/docs/DatasetPreparation.md

**Comment by SherHype** [comment]
Thank you very much for your reply! If I want to use my own blurry single photo on your model for super resolution, how do I manipulate the processed image?0.0

**Comment by Zj-BinXia** [comment]
you can revise the corresponding test yml file with 

test_1:
    name: test
    type: SingleImageDataset
    dataroot_lq: /dataset/LR
    io_backend:
      type: disk

**Comment by SherHype** [comment]
Thank you very much for your answer! You are so friendly! Another question I want to ask, if I want to modify the part of your model about binarization, can I just modify the content in the quant_convs_bbcu.py, or do I need to modify something else?

**Comment by Zj-BinXia** [comment]
That's depending on what you modify. You may also modify yml and model files.
