### ISSUE TITLE
Question about BBCU-H & BBCU-T

### ISSUE THREAD

**Issue by WooKyoungHan** [Zj-BinXia/BBCU#4]
Hi, I appreciate sharing codes for your novel paper.

I have a question about the detailed structure of the code, especially for the head and tail parts of the BBCU network.
My question is, while the main paper demonstrates that the header and tail part have Binary convolutions, your codes implemented with nn.Conv2d module. Please let me know if I have any misunderstanding.

Again, I appreciate your novel codes for pioneering BNNs. :)

**Comment by Zj-BinXia** [comment]
![image](https://github.com/Zj-BinXia/BBCU/assets/95993353/82be7fd0-7039-412a-a681-f6e33d96ed5c)
Yes, in my experiments for the paper, I found that quantizing the body and upsampling parts yielded significant benefits, while quantizing the head and tail provided relatively lower benefits. Therefore, I offer a network that only quantizes the body and upsampling sections.

**Comment by WooKyoungHan** [comment]
Oops, sorry for my misunderstanding. Thanks for the answer :D
